# Generated by Django 4.2 on 2023-04-16 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('stars', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255)),
                ('memo', models.TextField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('curpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curpoint', to='reviews.point')),
                ('intpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intpoint', to='reviews.point')),
                ('naapoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naapoint', to='reviews.point')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.shop')),
                ('ovrpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ovrpoint', to='reviews.point')),
                ('serpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serpoint', to='reviews.point')),
                ('toipoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toipoint', to='reviews.point')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
